version: "3"

services:
  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - app
  app:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    image: frontend
    container_name: frontend
    environment:
      - API_HOST=http://3.219.220.166:5000
    restart: always
    volumes:
      - ./src:/app/src
    ports:
      - 80:7000
